version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: service_provider/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: uvicorn service_provider.app.main:app --host 0.0.0.0 --port 8080 --reload